trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.7.0'
  AWS_REGION: 'us-east-1'

steps:
  - task: TerraformInstaller@1
    displayName: "Install Terraform"
    inputs:
      terraformVersion: $(TF_VERSION)

# Detect which TFVars file changed
  - task: Bash@3
    inputs:
      targetType: inline
      script: |
        echo "Detecting environment based on changed files..."

        git fetch origin $BUILD_SOURCEBRANCHNAME --depth=2

        CHANGED=$(git diff --name-only HEAD~1 HEAD)

        echo "Changed files:"
        echo "$CHANGED"

        DEV_CHANGED=false
        PROD_CHANGED=false

        if echo "$CHANGED" | grep -q "environment/dev.tfvars"; then
          DEV_CHANGED=true
        fi

        if echo "$CHANGED" | grep -q "environment/prod.tfvars"; then
          PROD_CHANGED=true
        fi

        if [ "$DEV_CHANGED" = true ] && [ "$PROD_CHANGED" = true ]; then
          echo "Both dev and prod tfvars changed. Aborting to avoid dual deploy."
          exit 1
        fi

        if [ "$DEV_CHANGED" = true ]; then
          echo "##vso[task.setvariable variable=TFVARS_FILE]environment/dev.tfvars"
          echo "##vso[task.setvariable variable=ENVIRONMENT]dev"
        elif [ "$PROD_CHANGED" = true ]; then
          echo "##vso[task.setvariable variable=TFVARS_FILE]environment/prod.tfvars"
          echo "##vso[task.setvariable variable=ENVIRONMENT]prod"
        else
          echo "No tfvars file changed. Nothing to deploy."
          exit 0
        fi

        echo "Environment selected: $(ENVIRONMENT)"
        echo "Using tfvars file: $(TFVARS_FILE)"

# Download tfvars from S3
  - task: Bash@3
    displayName: "Download tfvars from S3"
    inputs:
      targetType: inline
      script: |
          echo "Downloading tfvars file from S3..."
          mkdir -p environment
          aws s3 cp s3://terraform/$(ENVIRONMENT).tfvars $(TFVARS_FILE)
          echo "Downloaded $(TFVARS_FILE) from S3 bucket 'terraform'"

# Configure AWS credentials
  - task: Bash@3
    displayName: "Configure AWS Credentials"
    inputs:
      targetType: inline
      script: |
        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        export AWS_DEFAULT_REGION=$(AWS_REGION)
  
# Terraform Init for our modules using the S3 remote backend
  - task: Bash@3
    displayName: "Run terraform init"
    inputs:
      targetType: inline
      script: |
        terraform init \
        -backend-config="key=state/$(ENVIRONMENT).tfstate"

  - task: Bash@3
    displayName: "Run terraform plan"
    inputs:
      targetType: inline
      script: |
        terraform plan -var-file=$(TFVARS_FILE)

  - task: Bash@3
    displayName: "Run terraform apply"
    inputs:
      targetType: inline
      script: |
        terraform apply -auto-approve tfplan
# We are dynamically creating the TFVARS_FILE at runtime within our bash detection script
# This is evident in lines like this: echo "##vso[task.setvariable variable=TFVARS_FILE]environment/dev.tfvars"
