#This file itself will be used at the ADO pipeline runtime via injection with the Terraform init cmd
#We are using separate S3 buckets, one for state and another for tfvars, to ensure security
bucket = "terraform"
key    = "tfstate/dev.tfstate"
region = "us-east-1"
